package com.agent.sbwnpcaddon.entity.client;

import com.agent.sbwnpcaddon.entity.EntityRegistry;
import com.agent.sbwnpcaddon.entity.client.IvNpcRenderer;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.client.event.EntityRenderersEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;

@Mod.EventBusSubscriber(modid = "sbw_npc_addon", bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
public class ClientSetup {
    @SubscribeEvent
    public static void registerRenderers(EntityRenderersEvent.RegisterRenderers event) {
        event.registerEntityRenderer(EntityRegistry.AA_12.get(), ctx -> new SbwNpcRenderer(ctx, "aa_12"));
        event.registerEntityRenderer(EntityRegistry.AH_6.get(), ctx -> new SbwNpcRenderer(ctx, "ah_6"));
        event.registerEntityRenderer(EntityRegistry.AK_12.get(), ctx -> new SbwNpcRenderer(ctx, "ak_12"));
        event.registerEntityRenderer(EntityRegistry.AK_47.get(), ctx -> new SbwNpcRenderer(ctx, "ak_47"));
        event.registerEntityRenderer(EntityRegistry.ANNIHILATOR.get(), ctx -> new SbwNpcRenderer(ctx, "annihilator"));
        event.registerEntityRenderer(EntityRegistry.AWM.get(), ctx -> new SbwNpcRenderer(ctx, "awm"));
        event.registerEntityRenderer(EntityRegistry.A_10A.get(), ctx -> new SbwNpcRenderer(ctx, "a_10a"));
        event.registerEntityRenderer(EntityRegistry.BL_132.get(), ctx -> new SbwNpcRenderer(ctx, "bl_132"));
        event.registerEntityRenderer(EntityRegistry.BMP_2.get(), ctx -> new SbwNpcRenderer(ctx, "bmp_2"));
        event.registerEntityRenderer(EntityRegistry.BOCEK.get(), ctx -> new SbwNpcRenderer(ctx, "bocek"));
        event.registerEntityRenderer(EntityRegistry.BRADLEY.get(), ctx -> new SbwNpcRenderer(ctx, "bradley"));
        event.registerEntityRenderer(EntityRegistry.CONTAINER.get(), ctx -> new SbwNpcRenderer(ctx, "container"));
        event.registerEntityRenderer(EntityRegistry.DEVOTION.get(), ctx -> new SbwNpcRenderer(ctx, "devotion"));
        event.registerEntityRenderer(EntityRegistry.DRONE.get(), ctx -> new SbwNpcRenderer(ctx, "drone"));
        event.registerEntityRenderer(EntityRegistry.GLOCK_17.get(), ctx -> new SbwNpcRenderer(ctx, "glock_17"));
        event.registerEntityRenderer(EntityRegistry.GLOCK_18.get(), ctx -> new SbwNpcRenderer(ctx, "glock_18"));
        event.registerEntityRenderer(EntityRegistry.GUN_MU.get(), ctx -> new SbwNpcRenderer(ctx, "gun_mu"));
        event.registerEntityRenderer(EntityRegistry.HK_416.get(), ctx -> new SbwNpcRenderer(ctx, "hk_416"));
        event.registerEntityRenderer(EntityRegistry.HOMEMADE_SHOTGUN.get(), ctx -> new SbwNpcRenderer(ctx, "homemade_shotgun"));
        event.registerEntityRenderer(EntityRegistry.HPJ_11.get(), ctx -> new SbwNpcRenderer(ctx, "hpj_11"));
        event.registerEntityRenderer(EntityRegistry.HUNTING_RIFLE.get(), ctx -> new SbwNpcRenderer(ctx, "hunting_rifle"));
        event.registerEntityRenderer(EntityRegistry.IGLA_9K38.get(), ctx -> new SbwNpcRenderer(ctx, "igla_9k38"));
        event.registerEntityRenderer(EntityRegistry.INSIDIOUS.get(), ctx -> new SbwNpcRenderer(ctx, "insidious"));
        event.registerEntityRenderer(EntityRegistry.JAVELIN.get(), ctx -> new SbwNpcRenderer(ctx, "javelin"));
        event.registerEntityRenderer(EntityRegistry.JU_87.get(), ctx -> new SbwNpcRenderer(ctx, "ju_87"));
        event.registerEntityRenderer(EntityRegistry.KV_16.get(), ctx -> new SbwNpcRenderer(ctx, "kv_16"));
        event.registerEntityRenderer(EntityRegistry.K_98.get(), ctx -> new SbwNpcRenderer(ctx, "k_98"));
        event.registerEntityRenderer(EntityRegistry.LASER_TOWER.get(), ctx -> new SbwNpcRenderer(ctx, "laser_tower"));
        event.registerEntityRenderer(EntityRegistry.LAV_150.get(), ctx -> new SbwNpcRenderer(ctx, "lav_150"));
        event.registerEntityRenderer(EntityRegistry.LAV_25.get(), ctx -> new SbwNpcRenderer(ctx, "lav_25"));
        event.registerEntityRenderer(EntityRegistry.LAV_AD.get(), ctx -> new SbwNpcRenderer(ctx, "lav_ad"));
        event.registerEntityRenderer(EntityRegistry.LUNGE_MINE.get(), ctx -> new SbwNpcRenderer(ctx, "lunge_mine"));
        event.registerEntityRenderer(EntityRegistry.M79.get(), ctx -> new SbwNpcRenderer(ctx, "m79"));
        event.registerEntityRenderer(EntityRegistry.MARLIN.get(), ctx -> new SbwNpcRenderer(ctx, "marlin"));
        event.registerEntityRenderer(EntityRegistry.MILITARY_SHOVEL.get(), ctx -> new SbwNpcRenderer(ctx, "military_shovel"));
        event.registerEntityRenderer(EntityRegistry.MINIGUN.get(), ctx -> new SbwNpcRenderer(ctx, "minigun"));
        event.registerEntityRenderer(EntityRegistry.MI_28.get(), ctx -> new SbwNpcRenderer(ctx, "mi_28"));
        event.registerEntityRenderer(EntityRegistry.MK_14.get(), ctx -> new SbwNpcRenderer(ctx, "mk_14"));
        event.registerEntityRenderer(EntityRegistry.MK_42.get(), ctx -> new SbwNpcRenderer(ctx, "mk_42"));
        event.registerEntityRenderer(EntityRegistry.MLE_1934.get(), ctx -> new SbwNpcRenderer(ctx, "mle_1934"));
        event.registerEntityRenderer(EntityRegistry.MORTAR.get(), ctx -> new SbwNpcRenderer(ctx, "mortar"));
        event.registerEntityRenderer(EntityRegistry.MOSIN_NAGANT.get(), ctx -> new SbwNpcRenderer(ctx, "mosin_nagant"));
        event.registerEntityRenderer(EntityRegistry.MP_443.get(), ctx -> new SbwNpcRenderer(ctx, "mp_443"));
        event.registerEntityRenderer(EntityRegistry.MP_5.get(), ctx -> new SbwNpcRenderer(ctx, "mp_5"));
        event.registerEntityRenderer(EntityRegistry.M_1911.get(), ctx -> new SbwNpcRenderer(ctx, "m_1911"));
        event.registerEntityRenderer(EntityRegistry.M_1A_2.get(), ctx -> new SbwNpcRenderer(ctx, "m_1a_2"));
        event.registerEntityRenderer(EntityRegistry.M_2_HB.get(), ctx -> new SbwNpcRenderer(ctx, "m_2_hb"));
        event.registerEntityRenderer(EntityRegistry.M_4.get(), ctx -> new SbwNpcRenderer(ctx, "m_4"));
        event.registerEntityRenderer(EntityRegistry.M_60.get(), ctx -> new SbwNpcRenderer(ctx, "m_60"));
        event.registerEntityRenderer(EntityRegistry.M_870.get(), ctx -> new SbwNpcRenderer(ctx, "m_870"));
        event.registerEntityRenderer(EntityRegistry.M_98B.get(), ctx -> new SbwNpcRenderer(ctx, "m_98b"));
        event.registerEntityRenderer(EntityRegistry.NTW_20.get(), ctx -> new SbwNpcRenderer(ctx, "ntw_20"));
        event.registerEntityRenderer(EntityRegistry.PLZ_05.get(), ctx -> new SbwNpcRenderer(ctx, "plz_05"));
        event.registerEntityRenderer(EntityRegistry.PRISM_TANK.get(), ctx -> new SbwNpcRenderer(ctx, "prism_tank"));
        event.registerEntityRenderer(EntityRegistry.PTKM_1R_ITEM.get(), ctx -> new SbwNpcRenderer(ctx, "ptkm_1r_item"));
        event.registerEntityRenderer(EntityRegistry.QBZ_191.get(), ctx -> new SbwNpcRenderer(ctx, "qbz_191"));
        event.registerEntityRenderer(EntityRegistry.QBZ_95.get(), ctx -> new SbwNpcRenderer(ctx, "qbz_95"));
        event.registerEntityRenderer(EntityRegistry.QL_1031.get(), ctx -> new SbwNpcRenderer(ctx, "ql_1031"));
        event.registerEntityRenderer(EntityRegistry.REPAIR_TOOL.get(), ctx -> new SbwNpcRenderer(ctx, "repair_tool"));
        event.registerEntityRenderer(EntityRegistry.RPG.get(), ctx -> new SbwNpcRenderer(ctx, "rpg"));
        event.registerEntityRenderer(EntityRegistry.RPK.get(), ctx -> new SbwNpcRenderer(ctx, "rpk"));
        event.registerEntityRenderer(EntityRegistry.SECONDARY_CATACLYSM.get(), ctx -> new SbwNpcRenderer(ctx, "secondary_cataclysm"));
        event.registerEntityRenderer(EntityRegistry.SENTINEL.get(), ctx -> new SbwNpcRenderer(ctx, "sentinel"));
        event.registerEntityRenderer(EntityRegistry.SKS.get(), ctx -> new SbwNpcRenderer(ctx, "sks"));
        event.registerEntityRenderer(EntityRegistry.SMALL_CONTAINER.get(), ctx -> new SbwNpcRenderer(ctx, "small_container"));
        event.registerEntityRenderer(EntityRegistry.SODAYO_PICK_UP.get(), ctx -> new SbwNpcRenderer(ctx, "sodayo_pick_up"));
        event.registerEntityRenderer(EntityRegistry.SODAYO_PICK_UP_HMG.get(), ctx -> new SbwNpcRenderer(ctx, "sodayo_pick_up_hmg"));
        event.registerEntityRenderer(EntityRegistry.SODAYO_PICK_UP_ROCKET.get(), ctx -> new SbwNpcRenderer(ctx, "sodayo_pick_up_rocket"));
        event.registerEntityRenderer(EntityRegistry.SODAYO_PICK_UP_TOW.get(), ctx -> new SbwNpcRenderer(ctx, "sodayo_pick_up_tow"));
        event.registerEntityRenderer(EntityRegistry.SPEEDBOAT.get(), ctx -> new SbwNpcRenderer(ctx, "speedboat"));
        event.registerEntityRenderer(EntityRegistry.SUPER_STAR_SHOOTER.get(), ctx -> new SbwNpcRenderer(ctx, "super_star_shooter"));
        event.registerEntityRenderer(EntityRegistry.SVD.get(), ctx -> new SbwNpcRenderer(ctx, "svd"));
        event.registerEntityRenderer(EntityRegistry.TASER.get(), ctx -> new SbwNpcRenderer(ctx, "taser"));
        event.registerEntityRenderer(EntityRegistry.TINY_SPEEDBOAT.get(), ctx -> new SbwNpcRenderer(ctx, "tiny_speedboat"));
        event.registerEntityRenderer(EntityRegistry.TM_62.get(), ctx -> new SbwNpcRenderer(ctx, "tm_62"));
        event.registerEntityRenderer(EntityRegistry.TOM_6.get(), ctx -> new SbwNpcRenderer(ctx, "tom_6"));
        event.registerEntityRenderer(EntityRegistry.TOW.get(), ctx -> new SbwNpcRenderer(ctx, "tow"));
        event.registerEntityRenderer(EntityRegistry.TRACHELIUM.get(), ctx -> new SbwNpcRenderer(ctx, "trachelium"));
        event.registerEntityRenderer(EntityRegistry.TRUCK.get(), ctx -> new SbwNpcRenderer(ctx, "truck"));
        event.registerEntityRenderer(EntityRegistry.TYPE_63.get(), ctx -> new SbwNpcRenderer(ctx, "type_63"));
        event.registerEntityRenderer(EntityRegistry.T_90A.get(), ctx -> new SbwNpcRenderer(ctx, "t_90a"));
        event.registerEntityRenderer(EntityRegistry.VECTOR.get(), ctx -> new SbwNpcRenderer(ctx, "vector"));
        event.registerEntityRenderer(EntityRegistry.VEHICLE_ASSEMBLING_TABLE.get(), ctx -> new SbwNpcRenderer(ctx, "vehicle_assembling_table"));
        event.registerEntityRenderer(EntityRegistry.VEHICLE_ASSEMBLING_TABLE_VEHICLE.get(), ctx -> new SbwNpcRenderer(ctx, "vehicle_assembling_table_vehicle"));
        event.registerEntityRenderer(EntityRegistry.WAVEFORCE_TOWER.get(), ctx -> new SbwNpcRenderer(ctx, "waveforce_tower"));
        event.registerEntityRenderer(EntityRegistry.WHEEL_CHAIR.get(), ctx -> new SbwNpcRenderer(ctx, "wheel_chair"));
        event.registerEntityRenderer(EntityRegistry.YX_100.get(), ctx -> new SbwNpcRenderer(ctx, "yx_100"));
        event.registerEntityRenderer(EntityRegistry.ZTZ_99A.get(), ctx -> new SbwNpcRenderer(ctx, "ztz_99a"));
        event.registerEntityRenderer(EntityRegistry.CHARGER.get(), ctx -> new IvNpcRenderer(ctx, "iv_charger"));
        event.registerEntityRenderer(EntityRegistry.CUSTOMBENCH.get(), ctx -> new IvNpcRenderer(ctx, "iv_custombench"));
        event.registerEntityRenderer(EntityRegistry.DECORBENCH.get(), ctx -> new IvNpcRenderer(ctx, "iv_decorbench"));
        event.registerEntityRenderer(EntityRegistry.ENGINEBENCH.get(), ctx -> new IvNpcRenderer(ctx, "iv_enginebench"));
        event.registerEntityRenderer(EntityRegistry.FUELPUMP.get(), ctx -> new IvNpcRenderer(ctx, "iv_fuelpump"));
        event.registerEntityRenderer(EntityRegistry.GUNBENCH.get(), ctx -> new IvNpcRenderer(ctx, "iv_gunbench"));
        event.registerEntityRenderer(EntityRegistry.INSTRUMENTBENCH.get(), ctx -> new IvNpcRenderer(ctx, "iv_instrumentbench"));
        event.registerEntityRenderer(EntityRegistry.INVISIBLE.get(), ctx -> new IvNpcRenderer(ctx, "iv_invisible"));
        event.registerEntityRenderer(EntityRegistry.ITEMBENCH.get(), ctx -> new IvNpcRenderer(ctx, "iv_itembench"));
        event.registerEntityRenderer(EntityRegistry.JERRYCAN.get(), ctx -> new IvNpcRenderer(ctx, "iv_jerrycan"));
        event.registerEntityRenderer(EntityRegistry.PROPELLERBENCH.get(), ctx -> new IvNpcRenderer(ctx, "iv_propellerbench"));
        event.registerEntityRenderer(EntityRegistry.SEATBENCH.get(), ctx -> new IvNpcRenderer(ctx, "iv_seatbench"));
        event.registerEntityRenderer(EntityRegistry.VEHICLEBENCH.get(), ctx -> new IvNpcRenderer(ctx, "iv_vehiclebench"));
        event.registerEntityRenderer(EntityRegistry.WHEELBENCH.get(), ctx -> new IvNpcRenderer(ctx, "iv_wheelbench"));
    }
}
